/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *vbox1;
  GtkWidget *drawingarea1;
  GtkWidget *hbuttonbox1;
  GtkWidget *but_play;
  GtkWidget *but_slow_down;
  GtkWidget *but_speed_up;
  GtkWidget *but_pause;
  GtkWidget *but_stop;
  GtkWidget *label1;
  AtkObject *atko;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_container_add (GTK_CONTAINER (window1), frame1);
  gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_NONE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), vbox1);

  drawingarea1 = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea1);
  gtk_box_pack_start (GTK_BOX (vbox1), drawingarea1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (drawingarea1, -1, 350);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, TRUE, TRUE, 0);

  but_play = gtk_button_new_with_mnemonic (_("Play"));
  gtk_widget_show (but_play);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), but_play);
  gtk_widget_set_size_request (but_play, -1, 45);
  GTK_WIDGET_SET_FLAGS (but_play, GTK_CAN_DEFAULT);

  but_slow_down = gtk_button_new_with_mnemonic (_("Slow down"));
  gtk_widget_show (but_slow_down);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), but_slow_down);
  gtk_widget_set_size_request (but_slow_down, -1, 45);
  GTK_WIDGET_SET_FLAGS (but_slow_down, GTK_CAN_DEFAULT);

  but_speed_up = gtk_button_new_with_mnemonic (_("Speed up"));
  gtk_widget_show (but_speed_up);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), but_speed_up);
  gtk_widget_set_size_request (but_speed_up, -1, 45);
  GTK_WIDGET_SET_FLAGS (but_speed_up, GTK_CAN_DEFAULT);

  but_pause = gtk_button_new_with_mnemonic (_("Pause"));
  gtk_widget_show (but_pause);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), but_pause);
  gtk_widget_set_size_request (but_pause, -1, 45);
  GTK_WIDGET_SET_FLAGS (but_pause, GTK_CAN_DEFAULT);

  but_stop = gtk_button_new_with_mnemonic (_("Stop"));
  gtk_widget_show (but_stop);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), but_stop);
  gtk_widget_set_size_request (but_stop, -1, 45);
  GTK_WIDGET_SET_FLAGS (but_stop, GTK_CAN_DEFAULT);

  label1 = gtk_label_new (_("<b>ECG</b>"));
  gtk_widget_show (label1);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label1);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_CENTER);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (on_window1_destroy),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "map",
                    G_CALLBACK (on_drawingarea1_expose_event),
                    NULL);
  g_signal_connect ((gpointer) but_play, "clicked",
                    G_CALLBACK (on_but_play_clicked),
                    NULL);
  g_signal_connect ((gpointer) but_slow_down, "clicked",
                    G_CALLBACK (on_but_slow_down_clicked),
                    NULL);
  g_signal_connect ((gpointer) but_speed_up, "clicked",
                    G_CALLBACK (on_but_speed_up_clicked),
                    NULL);
  g_signal_connect ((gpointer) but_pause, "clicked",
                    G_CALLBACK (on_but_pause_clicked),
                    NULL);
  g_signal_connect ((gpointer) but_stop, "clicked",
                    G_CALLBACK (on_but_stop_clicked),
                    NULL);

  atko = gtk_widget_get_accessible (label1);
  atk_object_set_name (atko, _("ECG"));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, drawingarea1, "drawingarea1");
  GLADE_HOOKUP_OBJECT (window1, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (window1, but_play, "but_play");
  GLADE_HOOKUP_OBJECT (window1, but_slow_down, "but_slow_down");
  GLADE_HOOKUP_OBJECT (window1, but_speed_up, "but_speed_up");
  GLADE_HOOKUP_OBJECT (window1, but_pause, "but_pause");
  GLADE_HOOKUP_OBJECT (window1, but_stop, "but_stop");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");

  return window1;
}

